version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_erp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - mini_erp_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: mini_erp_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mini_erp_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mini_erp_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mini_erp
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: mini_erp_pass
      MYSQL_USER: mini_erp_user
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mini_erp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mini_erp_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - mysql
    networks:
      - mini_erp_network

volumes:
  mysql_data:

networks:
  mini_erp_network:
    driver: bridge
